// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1IQd8I7Jepgn4P912HZkZ2qnNI3sYDzE',
    appId: '1:684126863896:web:0a674a8aa1f8b983dfb96d',
    messagingSenderId: '684126863896',
    projectId: 'qr-ticket-4bb18',
    authDomain: 'qr-ticket-4bb18.firebaseapp.com',
    storageBucket: 'qr-ticket-4bb18.firebasestorage.app',
    measurementId: 'G-CKB5403T2F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkqWFNeVD3-lWWQgwqpIm9jgrIqkalXIE',
    appId: '1:684126863896:android:cd947ef37b6b3305dfb96d',
    messagingSenderId: '684126863896',
    projectId: 'qr-ticket-4bb18',
    storageBucket: 'qr-ticket-4bb18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDt9GurANZz2gYrCXK2M5Y-7_ZUaB44i3s',
    appId: '1:684126863896:ios:3af503d312f1a322dfb96d',
    messagingSenderId: '684126863896',
    projectId: 'qr-ticket-4bb18',
    storageBucket: 'qr-ticket-4bb18.firebasestorage.app',
    iosBundleId: 'com.example.qrticket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDt9GurANZz2gYrCXK2M5Y-7_ZUaB44i3s',
    appId: '1:684126863896:ios:3af503d312f1a322dfb96d',
    messagingSenderId: '684126863896',
    projectId: 'qr-ticket-4bb18',
    storageBucket: 'qr-ticket-4bb18.firebasestorage.app',
    iosBundleId: 'com.example.qrticket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1IQd8I7Jepgn4P912HZkZ2qnNI3sYDzE',
    appId: '1:684126863896:web:ea1bd6ae73c56410dfb96d',
    messagingSenderId: '684126863896',
    projectId: 'qr-ticket-4bb18',
    authDomain: 'qr-ticket-4bb18.firebaseapp.com',
    storageBucket: 'qr-ticket-4bb18.firebasestorage.app',
    measurementId: 'G-S21ZENBSMD',
  );
}
